//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregateCap) DeepCopyInto(out *AggregateCap) {
	*out = *in
	if in.Envelopes != nil {
		in, out := &in.Envelopes, &out.Envelopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxConcurrency != nil {
		in, out := &in.MaxConcurrency, &out.MaxConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.MaxGPUHours != nil {
		in, out := &in.MaxGPUHours, &out.MaxGPUHours
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregateCap.
func (in *AggregateCap) DeepCopy() *AggregateCap {
	if in == nil {
		return nil
	}
	out := new(AggregateCap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregateHeadroom) DeepCopyInto(out *AggregateHeadroom) {
	*out = *in
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.GPUHours != nil {
		in, out := &in.GPUHours, &out.GPUHours
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregateHeadroom.
func (in *AggregateHeadroom) DeepCopy() *AggregateHeadroom {
	if in == nil {
		return nil
	}
	out := new(AggregateHeadroom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRenewSchedule) DeepCopyInto(out *AutoRenewSchedule) {
	*out = *in
	out.Period = in.Period
	out.NotifyBefore = in.NotifyBefore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRenewSchedule.
func (in *AutoRenewSchedule) DeepCopy() *AutoRenewSchedule {
	if in == nil {
		return nil
	}
	out := new(AutoRenewSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget {
	if in == nil {
		return nil
	}
	out := new(Budget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Budget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetEnvelope) DeepCopyInto(out *BudgetEnvelope) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxGPUHours != nil {
		in, out := &in.MaxGPUHours, &out.MaxGPUHours
		*out = new(int64)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = (*in).DeepCopy()
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = (*in).DeepCopy()
	}
	if in.PreActivation != nil {
		in, out := &in.PreActivation, &out.PreActivation
		*out = new(PreActivationPolicy)
		**out = **in
	}
	if in.Lending != nil {
		in, out := &in.Lending, &out.Lending
		*out = new(LendingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetEnvelope.
func (in *BudgetEnvelope) DeepCopy() *BudgetEnvelope {
	if in == nil {
		return nil
	}
	out := new(BudgetEnvelope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetList) DeepCopyInto(out *BudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Budget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetList.
func (in *BudgetList) DeepCopy() *BudgetList {
	if in == nil {
		return nil
	}
	out := new(BudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	if in.Envelopes != nil {
		in, out := &in.Envelopes, &out.Envelopes
		*out = make([]BudgetEnvelope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AggregateCaps != nil {
		in, out := &in.AggregateCaps, &out.AggregateCaps
		*out = make([]AggregateCap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parents != nil {
		in, out := &in.Parents, &out.Parents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoRenew != nil {
		in, out := &in.AutoRenew, &out.AutoRenew
		*out = new(AutoRenewSchedule)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
	if in.Headroom != nil {
		in, out := &in.Headroom, &out.Headroom
		*out = make([]EnvelopeHeadroom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AggregateHeadroom != nil {
		in, out := &in.AggregateHeadroom, &out.AggregateHeadroom
		*out = make([]AggregateHeadroom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = make([]EnvelopeUsage, len(*in))
		copy(*out, *in)
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.PendingRenewals != nil {
		in, out := &in.PendingRenewals, &out.PendingRenewals
		*out = make([]EnvelopeRenewalDue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopeHeadroom) DeepCopyInto(out *EnvelopeHeadroom) {
	*out = *in
	if in.GPUHours != nil {
		in, out := &in.GPUHours, &out.GPUHours
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopeHeadroom.
func (in *EnvelopeHeadroom) DeepCopy() *EnvelopeHeadroom {
	if in == nil {
		return nil
	}
	out := new(EnvelopeHeadroom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopeRenewalDue) DeepCopyInto(out *EnvelopeRenewalDue) {
	*out = *in
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopeRenewalDue.
func (in *EnvelopeRenewalDue) DeepCopy() *EnvelopeRenewalDue {
	if in == nil {
		return nil
	}
	out := new(EnvelopeRenewalDue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopeUsage) DeepCopyInto(out *EnvelopeUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopeUsage.
func (in *EnvelopeUsage) DeepCopy() *EnvelopeUsage {
	if in == nil {
		return nil
	}
	out := new(EnvelopeUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntendedSlice) DeepCopyInto(out *IntendedSlice) {
	*out = *in
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntendedSlice.
func (in *IntendedSlice) DeepCopy() *IntendedSlice {
	if in == nil {
		return nil
	}
	out := new(IntendedSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lease) DeepCopyInto(out *Lease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lease.
func (in *Lease) DeepCopy() *Lease {
	if in == nil {
		return nil
	}
	out := new(Lease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Lease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseInterval) DeepCopyInto(out *LeaseInterval) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseInterval.
func (in *LeaseInterval) DeepCopy() *LeaseInterval {
	if in == nil {
		return nil
	}
	out := new(LeaseInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseList) DeepCopyInto(out *LeaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Lease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseList.
func (in *LeaseList) DeepCopy() *LeaseList {
	if in == nil {
		return nil
	}
	out := new(LeaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseSlice) DeepCopyInto(out *LeaseSlice) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseSlice.
func (in *LeaseSlice) DeepCopy() *LeaseSlice {
	if in == nil {
		return nil
	}
	out := new(LeaseSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseSpec) DeepCopyInto(out *LeaseSpec) {
	*out = *in
	out.RunRef = in.RunRef
	if in.CompPath != nil {
		in, out := &in.CompPath, &out.CompPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Slice.DeepCopyInto(&out.Slice)
	in.Interval.DeepCopyInto(&out.Interval)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseSpec.
func (in *LeaseSpec) DeepCopy() *LeaseSpec {
	if in == nil {
		return nil
	}
	out := new(LeaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseStatus) DeepCopyInto(out *LeaseStatus) {
	*out = *in
	if in.Ended != nil {
		in, out := &in.Ended, &out.Ended
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseStatus.
func (in *LeaseStatus) DeepCopy() *LeaseStatus {
	if in == nil {
		return nil
	}
	out := new(LeaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LendingPolicy) DeepCopyInto(out *LendingPolicy) {
	*out = *in
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxConcurrency != nil {
		in, out := &in.MaxConcurrency, &out.MaxConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.MaxGPUHours != nil {
		in, out := &in.MaxGPUHours, &out.MaxGPUHours
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LendingPolicy.
func (in *LendingPolicy) DeepCopy() *LendingPolicy {
	if in == nil {
		return nil
	}
	out := new(LendingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreActivationPolicy) DeepCopyInto(out *PreActivationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreActivationPolicy.
func (in *PreActivationPolicy) DeepCopy() *PreActivationPolicy {
	if in == nil {
		return nil
	}
	out := new(PreActivationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation) DeepCopyInto(out *Reservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation.
func (in *Reservation) DeepCopy() *Reservation {
	if in == nil {
		return nil
	}
	out := new(Reservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Reservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationForecast) DeepCopyInto(out *ReservationForecast) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Remedies != nil {
		in, out := &in.Remedies, &out.Remedies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationForecast.
func (in *ReservationForecast) DeepCopy() *ReservationForecast {
	if in == nil {
		return nil
	}
	out := new(ReservationForecast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationList) DeepCopyInto(out *ReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Reservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationList.
func (in *ReservationList) DeepCopy() *ReservationList {
	if in == nil {
		return nil
	}
	out := new(ReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSpec) DeepCopyInto(out *ReservationSpec) {
	*out = *in
	out.RunRef = in.RunRef
	in.IntendedSlice.DeepCopyInto(&out.IntendedSlice)
	in.EarliestStart.DeepCopyInto(&out.EarliestStart)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSpec.
func (in *ReservationSpec) DeepCopy() *ReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationStatus) DeepCopyInto(out *ReservationStatus) {
	*out = *in
	if in.ActivatedAt != nil {
		in, out := &in.ActivatedAt, &out.ActivatedAt
		*out = (*in).DeepCopy()
	}
	if in.ReleasedAt != nil {
		in, out := &in.ReleasedAt, &out.ReleasedAt
		*out = (*in).DeepCopy()
	}
	if in.CanceledAt != nil {
		in, out := &in.CanceledAt, &out.CanceledAt
		*out = (*in).DeepCopy()
	}
	if in.CountdownSeconds != nil {
		in, out := &in.CountdownSeconds, &out.CountdownSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Forecast != nil {
		in, out := &in.Forecast, &out.Forecast
		*out = new(ReservationForecast)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationStatus.
func (in *ReservationStatus) DeepCopy() *ReservationStatus {
	if in == nil {
		return nil
	}
	out := new(ReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Run) DeepCopyInto(out *Run) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Run.
func (in *Run) DeepCopy() *Run {
	if in == nil {
		return nil
	}
	out := new(Run)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Run) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunETA) DeepCopyInto(out *RunETA) {
	*out = *in
	in.EstimatedCompletion.DeepCopyInto(&out.EstimatedCompletion)
	in.ReportedAt.DeepCopyInto(&out.ReportedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunETA.
func (in *RunETA) DeepCopy() *RunETA {
	if in == nil {
		return nil
	}
	out := new(RunETA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunFollow) DeepCopyInto(out *RunFollow) {
	*out = *in
	if in.After != nil {
		in, out := &in.After, &out.After
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpstreamFailureGrace != nil {
		in, out := &in.UpstreamFailureGrace, &out.UpstreamFailureGrace
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunFollow.
func (in *RunFollow) DeepCopy() *RunFollow {
	if in == nil {
		return nil
	}
	out := new(RunFollow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunFunding) DeepCopyInto(out *RunFunding) {
	*out = *in
	if in.MaxBorrowGPUs != nil {
		in, out := &in.MaxBorrowGPUs, &out.MaxBorrowGPUs
		*out = new(int32)
		**out = **in
	}
	if in.Sponsors != nil {
		in, out := &in.Sponsors, &out.Sponsors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunFunding.
func (in *RunFunding) DeepCopy() *RunFunding {
	if in == nil {
		return nil
	}
	out := new(RunFunding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunFundingLenderShare) DeepCopyInto(out *RunFundingLenderShare) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunFundingLenderShare.
func (in *RunFundingLenderShare) DeepCopy() *RunFundingLenderShare {
	if in == nil {
		return nil
	}
	out := new(RunFundingLenderShare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunFundingStatus) DeepCopyInto(out *RunFundingStatus) {
	*out = *in
	if in.Lenders != nil {
		in, out := &in.Lenders, &out.Lenders
		*out = make([]RunFundingLenderShare, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunFundingStatus.
func (in *RunFundingStatus) DeepCopy() *RunFundingStatus {
	if in == nil {
		return nil
	}
	out := new(RunFundingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunList) DeepCopyInto(out *RunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Run, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunList.
func (in *RunList) DeepCopy() *RunList {
	if in == nil {
		return nil
	}
	out := new(RunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunLocality) DeepCopyInto(out *RunLocality) {
	*out = *in
	if in.GroupGPUs != nil {
		in, out := &in.GroupGPUs, &out.GroupGPUs
		*out = new(int32)
		**out = **in
	}
	if in.AllowCrossGroupSpread != nil {
		in, out := &in.AllowCrossGroupSpread, &out.AllowCrossGroupSpread
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunLocality.
func (in *RunLocality) DeepCopy() *RunLocality {
	if in == nil {
		return nil
	}
	out := new(RunLocality)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunMalleability) DeepCopyInto(out *RunMalleability) {
	*out = *in
	if in.DesiredTotalGPUs != nil {
		in, out := &in.DesiredTotalGPUs, &out.DesiredTotalGPUs
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunMalleability.
func (in *RunMalleability) DeepCopy() *RunMalleability {
	if in == nil {
		return nil
	}
	out := new(RunMalleability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunReference) DeepCopyInto(out *RunReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunReference.
func (in *RunReference) DeepCopy() *RunReference {
	if in == nil {
		return nil
	}
	out := new(RunReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunResources) DeepCopyInto(out *RunResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunResources.
func (in *RunResources) DeepCopy() *RunResources {
	if in == nil {
		return nil
	}
	out := new(RunResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunRole) DeepCopyInto(out *RunRole) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.GroupGPUs != nil {
		in, out := &in.GroupGPUs, &out.GroupGPUs
		*out = new(int32)
		**out = **in
	}
	if in.Spares != nil {
		in, out := &in.Spares, &out.Spares
		*out = new(int32)
		**out = **in
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int32)
		**out = **in
	}
	if in.Backoff != nil {
		in, out := &in.Backoff, &out.Backoff
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunRole.
func (in *RunRole) DeepCopy() *RunRole {
	if in == nil {
		return nil
	}
	out := new(RunRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunRuntime) DeepCopyInto(out *RunRuntime) {
	*out = *in
	out.Checkpoint = in.Checkpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunRuntime.
func (in *RunRuntime) DeepCopy() *RunRuntime {
	if in == nil {
		return nil
	}
	out := new(RunRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunSpec) DeepCopyInto(out *RunSpec) {
	*out = *in
	out.Resources = in.Resources
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]RunRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = new(RunLocality)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RunRuntime)
		**out = **in
	}
	if in.Malleable != nil {
		in, out := &in.Malleable, &out.Malleable
		*out = new(RunMalleability)
		(*in).DeepCopyInto(*out)
	}
	if in.Funding != nil {
		in, out := &in.Funding, &out.Funding
		*out = new(RunFunding)
		(*in).DeepCopyInto(*out)
	}
	if in.Spares != nil {
		in, out := &in.Spares, &out.Spares
		*out = new(int32)
		**out = **in
	}
	if in.Follow != nil {
		in, out := &in.Follow, &out.Follow
		*out = new(RunFollow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunSpec.
func (in *RunSpec) DeepCopy() *RunSpec {
	if in == nil {
		return nil
	}
	out := new(RunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunStatus) DeepCopyInto(out *RunStatus) {
	*out = *in
	if in.PendingReservation != nil {
		in, out := &in.PendingReservation, &out.PendingReservation
		*out = new(string)
		**out = **in
	}
	if in.EarliestStart != nil {
		in, out := &in.EarliestStart, &out.EarliestStart
		*out = (*in).DeepCopy()
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(RunWidthStatus)
		**out = **in
	}
	if in.Funding != nil {
		in, out := &in.Funding, &out.Funding
		*out = new(RunFundingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ETA != nil {
		in, out := &in.ETA, &out.ETA
		*out = new(RunETA)
		(*in).DeepCopyInto(*out)
	}
	if in.FollowDeadline != nil {
		in, out := &in.FollowDeadline, &out.FollowDeadline
		*out = (*in).DeepCopy()
	}
	if in.CheckpointDeadline != nil {
		in, out := &in.CheckpointDeadline, &out.CheckpointDeadline
		*out = (*in).DeepCopy()
	}
	if in.RetryAfter != nil {
		in, out := &in.RetryAfter, &out.RetryAfter
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunStatus.
func (in *RunStatus) DeepCopy() *RunStatus {
	if in == nil {
		return nil
	}
	out := new(RunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunWidthStatus) DeepCopyInto(out *RunWidthStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunWidthStatus.
func (in *RunWidthStatus) DeepCopy() *RunWidthStatus {
	if in == nil {
		return nil
	}
	out := new(RunWidthStatus)
	in.DeepCopyInto(out)
	return out
}
